name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-name: Linux
            artifact-extension: .tar.gz
            build-command: cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_OPTIMIZATION_FAST_MATH=ON -DAPPEND_VERSION=ON -DAPPEND_VERSION_USE_GIT=OFF .
            archive-command: tar -czvf
          - os: windows-latest
            build-name: Windows
            artifact-extension: .zip
            build-command: cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_OPTIMIZATION_FAST_MATH=ON -DAPPEND_VERSION=ON -DAPPEND_VERSION_USE_GIT=OFF -G "MinGW Makefiles" .
            archive-command: 7z a

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup Clang (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14"
          
      - name: Install 7-Zip (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install 7zip

      - name: Setup MinGW-LLVM (Windows)
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Create build directory
        run: mkdir build

      - name: Change to build directory
        run: cd build

      - name: Configure CMake
        run: ${{ matrix.build-command }}

      - name: Build
        run: cmake --build .

      - name: Archive Artifacts
        run: |
          executable_name=$(echo Zagreus-v*)
          mkdir rel
          cp "$executable_name" rel/
          cp LICENSE README.md rel/
          cp -r . "rel/$executable_name-source-code"
          cd rel
          ${{ matrix.archive-command }} "../$executable_name${{ matrix.artifact-extension }}" *

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build-name }}
          path: "../$executable_name${{ matrix.artifact-extension }}"

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
  
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
